// Generated by SR-Infra scripts/build-tokens.mjs from design/tokens.json. Do not edit.
//
// Plain data, no UIKit or SwiftUI, so the app, widget, Live Activity and
// watch targets all compile it. Sizes are points (1rem = 16pt); tracking is
// in em, multiply by the font size. Theme.swift turns these into Colors.

public struct SRRGBA: Sendable, Equatable {
    public let hex: UInt32
    public let alpha: Double
    public init(_ hex: UInt32, _ alpha: Double = 1) { self.hex = hex; self.alpha = alpha }
    public var red: Double { Double((hex >> 16) & 0xFF) / 255 }
    public var green: Double { Double((hex >> 8) & 0xFF) / 255 }
    public var blue: Double { Double(hex & 0xFF) / 255 }
}

public struct SRTokenColour: Sendable, Equatable {
    public let light: SRRGBA
    public let dark: SRRGBA
}

public enum SRTokens {
    public enum Colour {
        public static let textPrimary = SRTokenColour(light: SRRGBA(0x1A1008), dark: SRRGBA(0xECE3D6))
        public static let textSecondary = SRTokenColour(light: SRRGBA(0x3D2E1A), dark: SRRGBA(0xCDC2B2))
        public static let textMuted = SRTokenColour(light: SRRGBA(0x1A1008, 0.65), dark: SRRGBA(0xECE3D6, 0.62))
        public static let textGhost = SRTokenColour(light: SRRGBA(0x1A1008, 0.45), dark: SRRGBA(0xECE3D6, 0.4))
        public static let accent = SRTokenColour(light: SRRGBA(0xC4570A), dark: SRRGBA(0xE07B2A))
        public static let accentHover = SRTokenColour(light: SRRGBA(0xA84808), dark: SRRGBA(0xF0913F))
        public static let accentTint04 = SRTokenColour(light: SRRGBA(0xC4570A, 0.04), dark: SRRGBA(0xE07B2A, 0.05))
        public static let accentTint08 = SRTokenColour(light: SRRGBA(0xC4570A, 0.08), dark: SRRGBA(0xE07B2A, 0.1))
        public static let accentTint14 = SRTokenColour(light: SRRGBA(0xC4570A, 0.14), dark: SRRGBA(0xE07B2A, 0.17))
        public static let accentTint20 = SRTokenColour(light: SRRGBA(0xC4570A, 0.2), dark: SRRGBA(0xE07B2A, 0.24))
        public static let accentTint25 = SRTokenColour(light: SRRGBA(0xC4570A, 0.25), dark: SRRGBA(0xE07B2A, 0.3))
        public static let accentTint35 = SRTokenColour(light: SRRGBA(0xC4570A, 0.35), dark: SRRGBA(0xE07B2A, 0.42))
        public static let accentTint50 = SRTokenColour(light: SRRGBA(0xC4570A, 0.5), dark: SRRGBA(0xE07B2A, 0.58))
        public static let accentOnDark = SRTokenColour(light: SRRGBA(0xE8863A), dark: SRRGBA(0xE8863A))
        public static let accentInk = SRTokenColour(light: SRRGBA(0x0E5B66), dark: SRRGBA(0x3FA3B0))
        public static let accentInkHover = SRTokenColour(light: SRRGBA(0x094850), dark: SRRGBA(0x094850))
        public static let accentInkOnDark = SRTokenColour(light: SRRGBA(0x7FB8C0), dark: SRRGBA(0x7FB8C0))
        public static let accentInkTint06 = SRTokenColour(light: SRRGBA(0x0E5B66, 0.06), dark: SRRGBA(0x3FA3B0, 0.08))
        public static let accentInkTint12 = SRTokenColour(light: SRRGBA(0x0E5B66, 0.12), dark: SRRGBA(0x3FA3B0, 0.14))
        public static let accentInkTint22 = SRTokenColour(light: SRRGBA(0x0E5B66, 0.22), dark: SRRGBA(0x3FA3B0, 0.24))
        public static let accentInkTint35 = SRTokenColour(light: SRRGBA(0x0E5B66, 0.35), dark: SRRGBA(0x3FA3B0, 0.38))
        public static let good = SRTokenColour(light: SRRGBA(0x55663A), dark: SRRGBA(0x55663A))
        public static let goodOnDark = SRTokenColour(light: SRRGBA(0x8A9A5B), dark: SRRGBA(0x8A9A5B))
        public static let goodLine = SRTokenColour(light: SRRGBA(0x6B7F4A, 0.6), dark: SRRGBA(0x6B7F4A, 0.6))
        public static let bg = SRTokenColour(light: SRRGBA(0xEDE4D4), dark: SRRGBA(0x14100C))
        public static let bgBase = SRTokenColour(light: SRRGBA(0xEDE4D4), dark: SRRGBA(0x14100C))
        public static let bgSection = SRTokenColour(light: SRRGBA(0x1A1008, 0.04), dark: SRRGBA(0xECE3D6, 0.04))
        public static let cardBg = SRTokenColour(light: SRRGBA(0x1A1008, 0.07), dark: SRRGBA(0xECE3D6, 0.06))
        public static let cardBorder = SRTokenColour(light: SRRGBA(0x1A1008, 0.18), dark: SRRGBA(0xECE3D6, 0.18))
        public static let divider = SRTokenColour(light: SRRGBA(0x1A1008, 0.08), dark: SRRGBA(0xECE3D6, 0.1))
        public static let codeBg = SRTokenColour(light: SRRGBA(0x1A1008), dark: SRRGBA(0x1A1008))
        public static let codeText = SRTokenColour(light: SRRGBA(0xEDE4D4), dark: SRRGBA(0xEDE4D4))
        public static let codeBorder = SRTokenColour(light: SRRGBA(0x1A1008, 0.3), dark: SRRGBA(0x1A1008, 0.3))
        public static let surfaceElevated = SRTokenColour(light: SRRGBA(0xE8DECE), dark: SRRGBA(0x1E1913))
        public static let surfaceOverlay = SRTokenColour(light: SRRGBA(0x1A1008, 0.05), dark: SRRGBA(0x1A1008, 0.05))
        public static let surfaceShell = SRTokenColour(light: SRRGBA(0xE9DFCD), dark: SRRGBA(0xE9DFCD))
        public static let surfaceRail = SRTokenColour(light: SRRGBA(0xE3D8C4), dark: SRRGBA(0xE3D8C4))
        public static let surfaceRailDeep = SRTokenColour(light: SRRGBA(0xE0D4BF), dark: SRRGBA(0xE0D4BF))
        public static let surfaceCard = SRTokenColour(light: SRRGBA(0xF3EBDD), dark: SRRGBA(0x231D16))
        public static let surfaceSunken = SRTokenColour(light: SRRGBA(0x1A1008, 0.035), dark: SRRGBA(0xECE3D6, 0.04))
        public static let lineHair = SRTokenColour(light: SRRGBA(0x1A1008, 0.1), dark: SRRGBA(0xECE3D6, 0.1))
        public static let line = SRTokenColour(light: SRRGBA(0x1A1008, 0.14), dark: SRRGBA(0xECE3D6, 0.14))
        public static let lineStrong = SRTokenColour(light: SRRGBA(0x1A1008, 0.16), dark: SRRGBA(0xECE3D6, 0.2))
        public static let chromeBg = SRTokenColour(light: SRRGBA(0x1A1008), dark: SRRGBA(0x0B0806))
        public static let chromeInk = SRTokenColour(light: SRRGBA(0xEDE4D4), dark: SRRGBA(0xECE3D6))
        public static let onInk05 = SRTokenColour(light: SRRGBA(0xEDE4D4, 0.05), dark: SRRGBA(0xEDE4D4, 0.05))
        public static let onInk08 = SRTokenColour(light: SRRGBA(0xEDE4D4, 0.08), dark: SRRGBA(0xEDE4D4, 0.08))
        public static let onInk12 = SRTokenColour(light: SRRGBA(0xEDE4D4, 0.12), dark: SRRGBA(0xEDE4D4, 0.12))
        public static let onInk14 = SRTokenColour(light: SRRGBA(0xEDE4D4, 0.14), dark: SRRGBA(0xEDE4D4, 0.14))
        public static let onInk16 = SRTokenColour(light: SRRGBA(0xEDE4D4, 0.16), dark: SRRGBA(0xEDE4D4, 0.16))
        public static let onInk30 = SRTokenColour(light: SRRGBA(0xEDE4D4, 0.3), dark: SRRGBA(0xEDE4D4, 0.3))
        public static let onInk45 = SRTokenColour(light: SRRGBA(0xEDE4D4, 0.45), dark: SRRGBA(0xEDE4D4, 0.45))
        public static let onInk55 = SRTokenColour(light: SRRGBA(0xEDE4D4, 0.55), dark: SRRGBA(0xEDE4D4, 0.55))
        public static let onInk70 = SRTokenColour(light: SRRGBA(0xEDE4D4, 0.7), dark: SRRGBA(0xEDE4D4, 0.7))
        public static let onInk80 = SRTokenColour(light: SRRGBA(0xEDE4D4, 0.8), dark: SRRGBA(0xEDE4D4, 0.8))
        public static let accentOnDark09 = SRTokenColour(light: SRRGBA(0xE8863A, 0.09), dark: SRRGBA(0xE8863A, 0.09))
        public static let accentOnDark40 = SRTokenColour(light: SRRGBA(0xE8863A, 0.4), dark: SRRGBA(0xE8863A, 0.4))
        public static let success = SRTokenColour(light: SRRGBA(0x2D7A3A), dark: SRRGBA(0x5EB36C))
        public static let successBg = SRTokenColour(light: SRRGBA(0x2D7A3A, 0.07), dark: SRRGBA(0x2D7A3A, 0.07))
        public static let successBorder = SRTokenColour(light: SRRGBA(0x2D7A3A, 0.5), dark: SRRGBA(0x2D7A3A, 0.5))
        public static let warn = SRTokenColour(light: SRRGBA(0xB0892A), dark: SRRGBA(0xD4AB4A))
        public static let warnBg = SRTokenColour(light: SRRGBA(0xB0892A, 0.07), dark: SRRGBA(0xB0892A, 0.07))
        public static let warnBorder = SRTokenColour(light: SRRGBA(0xB0892A, 0.5), dark: SRRGBA(0xB0892A, 0.5))
        public static let info = SRTokenColour(light: SRRGBA(0x0E5B66), dark: SRRGBA(0x3FA3B0))
        public static let infoBg = SRTokenColour(light: SRRGBA(0x0E5B66, 0.06), dark: SRRGBA(0x3FA3B0, 0.08))
        public static let infoBorder = SRTokenColour(light: SRRGBA(0x0E5B66, 0.35), dark: SRRGBA(0x3FA3B0, 0.38))
        public static let error = SRTokenColour(light: SRRGBA(0xCC4444), dark: SRRGBA(0xE06A6A))
        public static let errorBg = SRTokenColour(light: SRRGBA(0xC44444, 0.07), dark: SRRGBA(0xC44444, 0.07))
        public static let errorBorder = SRTokenColour(light: SRRGBA(0xC44444, 0.5), dark: SRRGBA(0xC44444, 0.5))
        public static let errorHover = SRTokenColour(light: SRRGBA(0xAA3333), dark: SRRGBA(0xAA3333))
        public static let trendDown = SRTokenColour(light: SRRGBA(0x8A3A08), dark: SRRGBA(0x8A3A08))
        public static let statusOk = SRTokenColour(light: SRRGBA(0x0E5B66), dark: SRRGBA(0x3FA3B0))
        public static let statusRun = SRTokenColour(light: SRRGBA(0xC4570A), dark: SRRGBA(0xE07B2A))
        public static let statusFail = SRTokenColour(light: SRRGBA(0xB3261E), dark: SRRGBA(0xB3261E))
        public static let chartCat1 = SRTokenColour(light: SRRGBA(0x7A5AA6), dark: SRRGBA(0x7A5AA6))
        public static let chartCat2 = SRTokenColour(light: SRRGBA(0xB4632E), dark: SRRGBA(0xB4632E))
        public static let chartCat3 = SRTokenColour(light: SRRGBA(0x3A8658), dark: SRRGBA(0x3A8658))
        public static let chartCat4 = SRTokenColour(light: SRRGBA(0x8A2D3A), dark: SRRGBA(0x8A2D3A))
        public static let chartSeries1 = SRTokenColour(light: SRRGBA(0xC4570A), dark: SRRGBA(0xE07B2A))
        public static let chartSeries2 = SRTokenColour(light: SRRGBA(0x0E5B66), dark: SRRGBA(0x3FA3B0))
        public static let chartArea = SRTokenColour(light: SRRGBA(0xC4570A, 0.14), dark: SRRGBA(0xE07B2A, 0.17))
        public static let chartGrid = SRTokenColour(light: SRRGBA(0x1A1008, 0.1), dark: SRRGBA(0xECE3D6, 0.1))
        public static let chartReference = SRTokenColour(light: SRRGBA(0x1A1008, 0.35), dark: SRRGBA(0xECE3D6, 0.35))
    }
    public enum FontSize {
        public static let fsTitleHero: Double = 36
        public static let fsTitleSection: Double = 28
        public static let fsFigure: Double = 34
        public static let fsDisplayHero: Double = 104
        public static let fsDisplayXl: Double = 132
        public static let fsDisplayLg: Double = 104
        public static let fsDisplayMd: Double = 72
        public static let fsDisplaySm: Double = 36
        public static let fsDisplayXs: Double = 22
        public static let fsNumXl: Double = 88
        public static let fsNumLg: Double = 54
        public static let fsNumMd: Double = 23
        public static let fsBodyLg: Double = 18
        public static let fsBody: Double = 16
        public static let fsBodySm: Double = 15
        public static let fsNav: Double = 14
        public static let fsLabel: Double = 13
        public static let fsLabelXs: Double = 12
    }
    public enum LineHeight {
        public static let lhDisplayHero: Double = 0.88
        public static let lhFigure: Double = 0.9
        public static let lhDisplay: Double = 0.94
        public static let lhBody: Double = 1.5
        public static let lhStrap: Double = 1.55
        public static let lhNote: Double = 1.7
    }
    public enum Tracking {
        public static let trackingDisplay: Double = -0.02
        public static let trackingKicker: Double = 0.18
        public static let trackingLabel: Double = 0.15
        public static let trackingControl: Double = 0.12
        public static let trackingChip: Double = 0.1
        public static let trackingSub: Double = 0.08
        public static let trackingNote: Double = 0.06
        public static let trackingLabelWide: Double = 0.16
    }
    public enum Space {
        public static let sp2: Double = 2
        public static let sp4: Double = 4
        public static let sp6: Double = 6
        public static let sp8: Double = 8
        public static let sp10: Double = 10
        public static let sp12: Double = 12
        public static let sp14: Double = 14
        public static let sp16: Double = 16
        public static let sp18: Double = 18
        public static let sp20: Double = 20
        public static let sp22: Double = 22
        public static let sp24: Double = 24
        public static let sp28: Double = 28
        public static let gutter: Double = 20
        public static let tilePad: Double = 18
        public static let tilePadPaper: Double = 20
        public static let panelPad: Double = 22
        public static let tileGap: Double = 14
        public static let panelGap: Double = 16
        public static let cardGap: Double = 18
        public static let splitGap: Double = 24
        public static let headGap: Double = 28
        public static let bandYHero: Double = 30
        public static let bandYSection: Double = 44
        public static let bandYDetail: Double = 30
    }
    public enum Radius {
        public static let radiusNone: Double = 0
        public static let radiusPill: Double = 100
        public static let radiusSharp: Double = 2
        public static let radiusGlass: Double = 26
        public static let radiusGlassInner: Double = 16
    }
}
